Update update_posts.yml

diff --git a/.github/workflows/update_posts.yml b/.github/workflows/update_posts.yml
--- a/.github/workflows/update_posts.yml
+++ b/.github/workflows/update_posts.yml
@@ -44,7 +44,19 @@ jobs:
           mv -f ./posts/* ./wiki/new_wiki
           rm -rf ./wiki/wiki
           mv -f ./wiki/new_wiki ./wiki/wiki
-          hunspell -d ro_RO -l -i utf-8 ./wiki/wiki/* || true
+          # Check for typos and store the result in a file
+          hunspell -d ro_RO -l -i utf-8 ./wiki/wiki/* > typos.txt || true
+          # If typos are found, create an issue with the list of typos and fail the action
+          if [ -s "typos.txt" ]; then
+            echo "Typos found:"
+            cat typos.txt
+            # Create issue using GitHub REST API
+            echo "Creating issue..."
+            echo "{\"title\":\"Typos found in wiki\",\"body\":\"Typos found: \n$(cat typos.txt)\"}" > issue.json
+            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d @issue.json "https://api.github.com/repos/cibucristi/wiki-website/issues"
+            # Fail the action
+            exit 1
+          fi
           cd wiki
           git config --global user.email "b-hood.ro@github.com"
           git config --global user.name "b-hood.ro"
