Update update_posts.yml

diff --git a/.github/workflows/update_posts.yml b/.github/workflows/update_posts.yml
--- a/.github/workflows/update_posts.yml
+++ b/.github/workflows/update_posts.yml
@@ -99,12 +99,18 @@ jobs:
               echo "Creating issue..."
               # Escape special characters in the issue body
               escaped_body=$(echo "$body" | jq -Rs 'gsub("\\\"";"\"")')
-              # Create issue with escaped body
-              issue_response=$(curl -X POST -H "Authorization: token ${{ secrets.CI_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"title\":\"Typos Found in Wiki\",\"body\":$escaped_body}" "https://api.github.com/repos/ragebhood/wiki/issues") || true
+              # Create issue with escaped body and capture the response
+              issue_response=$(curl -s -X POST -H "Authorization: token ${{ secrets.CI_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"title\":\"Typos Found in Wiki\",\"body\":$escaped_body}" "https://api.github.com/repos/ragebhood/wiki/issues") || true
               
               # Debugging statement to check the issue response
               echo "Issue Response:"
               echo "$issue_response"
+              
+              # Check if there are any errors in the issue response
+              if [[ "$issue_response" == *"errors"* ]]; then
+                  echo "Error creating issue. Please check the GitHub API response for details."
+                  exit 1
+              fi
               
               # Get the issue number from the response
               issue_number=$(echo "$issue_response" | jq -r '.number')
@@ -117,8 +123,8 @@ jobs:
                   # Escape special characters in the message body
                   escaped_message=$(echo "$typo_chunk" | jq -Rs 'gsub("\\\"";"\"")')
                   # Send message with escaped body
-                  curl -X POST -H "Authorization: token ${{ secrets.CI_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"body\":$escaped_message}" "https://api.github.com/repos/ragebhood/wiki/issues/$issue_number/comments" || true
-              done < <(split -l 50 filtered_typos.txt)
+                  curl -s -X POST -H "Authorization: token ${{ secrets.CI_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"body\":$escaped_message}" "https://api.github.com/repos/ragebhood/wiki/issues/$issue_number/comments" || true
+              done < <(tail -n +2 filtered_typos.txt)
               
               # Fail the action
               exit 1
